//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scanf.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty method could be removed.
        /// </summary>
        internal static string SFA_1002_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SFA_1002_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is empty.
        /// </summary>
        internal static string SFA_1002_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SFA_1002_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is empty.
        /// </summary>
        internal static string SFA_1002_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SFA_1002_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible not implemented functionality.
        /// </summary>
        internal static string SFA_1003_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SFA_1003_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible not implemented functionaliry.
        /// </summary>
        internal static string SFA_1003_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SFA_1003_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unattended Todo.
        /// </summary>
        internal static string SFA_1003_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SFA_1003_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure Methods should not be void.
        /// </summary>
        internal static string SFA_1004_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SFA_1004_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure method should not be void.
        /// </summary>
        internal static string SFA_1004_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SFA_1004_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure Method does not return a value.
        /// </summary>
        internal static string SFA_1004_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SFA_1004_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method should not return void.
        /// </summary>
        internal static string SFA_1005_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SFA_1005_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method &apos;{0}&apos; should not return void.
        /// </summary>
        internal static string SFA_1005_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SFA_1005_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async void method detected.
        /// </summary>
        internal static string SFA_1005_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SFA_1005_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename method with Async Suffix.
        /// </summary>
        internal static string SFA_1008_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SFA_1008_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename method &apos;{0}&apos; with Async suffix.
        /// </summary>
        internal static string SFA_1008_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SFA_1008_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename method with Async Suffix.
        /// </summary>
        internal static string SFA_1008_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SFA_1008_AnalyzerTitle", resourceCulture);
            }
        }
    }
}
